//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hesaplar()
        {
            this.Kartlar = new HashSet<Kartlar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Musteri_ID { get; set; }
        public string IBAN { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kartlar> Kartlar { get; set; }
    }
}
