//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kartlar
    {
        public int ID { get; set; }
        public Nullable<int> Hesap_ID { get; set; }
        public string KartNo { get; set; }
        public string SonKullanmaAy { get; set; }
        public string SonKullanmaYil { get; set; }
        public string CVCKodu { get; set; }
    
        public virtual Hesaplar Hesaplar { get; set; }
    }
}
